name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: root
          POSTGRES_DB: simple_Bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.13.8

      - name: Build
        run: go build -v ./...

      -name: Run migrations
          run: make migrateup

      - name: Test
        run: make test
